#networks:
#    base_default:
#      external: true
#    backend:
#      driver: bridge
services:
  nginx:
    image: nginx
#    labels:
#        com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .nginx/data/conf.d:/etc/nginx/conf.d
      - .nginx/data/vhost.d:/etc/nginx/vhost.d
      - .nginx/data/html:/usr/share/nginx/html
      - .nginx/data/certs:/etc/nginx/certs:ro
#      - .php:/php

  nginx-gen:
    image: jwilder/docker-gen
    command: -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    container_name: nginx-gen
    restart: unless-stopped
    volumes:
      - .nginx/data/conf.d:/etc/nginx/conf.d
      - .nginx/data/vhost.d:/etc/nginx/vhost.d
      - .nginx/data/html:/usr/share/nginx/html
      - .nginx/data/certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
  db:
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_DB=db
    image: postgres:10
    restart: unless-stopped
#    networks:
#      backend:
#        aliases:
#          - pg10
    volumes:
      - .db/data/:/var/lib/postgresql/data
#      - .db/socket/:/var/run/postgresql/
    ports:
      - 5432:5432
  odoo:
    build: odoo
#    image: docky_club3d11_odoo:latest
    environment:
      - MIGRATE=false
      - PYTHONDONTWRITEBYTECODE=True
      - LOCAL_USER_ID=1001
      - DB_USER=odoo
      - DB_PASS=odoo
      - DB_NAME=club01
      - ADMIN_PASSWD=ButNoS1mpler
      - RUNNING_ENV=dev
      - LIST_DB=True
#     - DEMO=False
      - LIMIT_TIME_CPU=60000
      - LIMIT_TIME_REAL=120000
      - DB_HOST=db
      - ADDONS_PATH=/odoo/local-src,/odoo/src/addons,/odoo/external-src/club3d-addons,/odoo/external-src/account-analytic,/odoo/external-src/account-closing,/odoo/external-src/account-consolidation,/odoo/external-src/account-financial-reporting,/odoo/external-src/account-financial-tools,/odoo/external-src/account-fiscal-rule,/odoo/external-src/account-invoicing,/odoo/external-src/bank-payment,/odoo/external-src/bank-statement-import,/odoo/external-src/calendar,/odoo/external-src/commission,/odoo/external-src/community-data-files,/odoo/external-src/connector-cmis,/odoo/external-src/connector-ecommerce,/odoo/external-src/connector-interfaces,/odoo/external-src/connector-magento,/odoo/external-src/connector-telephony,/odoo/external-src/connector,/odoo/external-src/contract,/odoo/external-src/crm,/odoo/external-src/data-protection,/odoo/external-src/delivery-carrier,/odoo/external-src/donation,/odoo/external-src/e-commerce,/odoo/external-src/edi,/odoo/external-src/event,/odoo/external-src/geospatial,/odoo/external-src/hr-timesheet,/odoo/external-src/hr,/odoo/external-src/knowledge,/odoo/external-src/l10n-netherlands,/odoo/external-src/maintenance,/odoo/external-src/management-system,/odoo/external-src/margin-analysis,/odoo/external-src/multi-company,/odoo/external-src/partner-contact,/odoo/external-src/product-attribute,/odoo/external-src/product-variant,/odoo/external-src/project-agile,/odoo/external-src/project-reporting,/odoo/external-src/project,/odoo/external-src/purchase-reporting,/odoo/external-src/purchase-workflow,/odoo/external-src/intrastat-extrastat,/odoo/external-src/reporting-engine,/odoo/external-src/rest-framework,/odoo/external-src/rma,/odoo/external-src/sale-financial,/odoo/external-src/sale-reporting,/odoo/external-src/sale-workflow,/odoo/external-src/server-auth,/odoo/external-src/social,/odoo/external-src/stock-logistics-barcode,/odoo/external-src/stock-logistics-reporting,/odoo/external-src/stock-logistics-transport,/odoo/external-src/stock-logistics-warehouse,/odoo/external-src/stock-logistics-workflow,/odoo/external-src/vertical-agriculture,/odoo/external-src/vertical-association,/odoo/external-src/vertical-construction,/odoo/external-src/vertical-edition,/odoo/external-src/vertical-education,/odoo/external-src/vertical-isp,/odoo/external-src/vertical-travel,/odoo/external-src/web,/odoo/external-src/webkit-tools,/odoo/external-src/website-cms,/odoo/external-src/account-reconcile,/odoo/external-src/mis-builder,/odoo/external-src/operating-unit,/odoo/external-src/queue,/odoo/external-src/server-tools,/odoo/external-src/server-ux,/odoo/external-src/server-backend,/odoo/external-src/odoo-usability,/odoo/external-src/ak-odoo-incubator
#      - MARABUNTA_MODE=demo
      - VIRTUAL_HOST=bo.club-3d.com
      - VIRTUAL_PORT=8069,8072/longpolling
#    user: odoo
    expose:
      - 8069
      - 8072
#    networks:
#      - backend
    volumes:
      - ./odoo:/odoo
#      - /home/voodoo/base/.db/socket/:/var/run/postgresql/
      - ./data/addons:/data/odoo/addons
      - ./data/filestore:/data/odoo/filestore
      - ./data/sessions:/data/odoo/sessions
    command: ["bash"]
    stdin_open: true
    tty: true
version: '3'
