version: "3.7"
networks:
  docky10wh_default:
    external: true
services:
  db10:
    environment:
      - POSTGRES_USER=$PGUSER
      - POSTGRES_DB=$PGDATABASE
    image: postgres:10.0
    restart: unless-stopped
    networks:
      - docky10wh_default
    volumes:
      - "data-db10:/var/lib/postgresql/data"
    ports:
      - 15432:5432
  odoo:
    build: odoo
    environment:
      - MIGRATE=false
      - PYTHONDONTWRITEBYTECODE=True
      - LOCAL_USER_ID=$UID
      - RUNNING_ENV=$ENV
      - DB_HOST=$PGHOST
      - DB_NAME=$PGDATABASE
      - DB_USER=$PGUSER
      - DB_PASS=$PGPASSWORD
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGUSER=$PGUSER
      - PGPASSWORD=$PGPASSWORD
      - DB_FILTER=xxx.*
      - ADMIN_PASSWD=ButNoS1mpler
      - LIST_DB=True
      - LIMIT_TIME_CPU=6000
      - LIMIT_TIME_REAL=12000
      - ADDONS_PATH=/odoo/local-src,/odoo/src/addons,/odoo/src/odoo/addons,/odoo/links,/odoo/external-src/account-analytic,/odoo/external-src/account-budgeting,/odoo/external-src/account-closing,/odoo/external-src/account-consolidation,/odoo/external-src/account-financial-reporting,/odoo/external-src/account-financial-tools,/odoo/external-src/account-fiscal-rule,/odoo/external-src/account-invoicing,/odoo/external-src/bank-payment,/odoo/external-src/bank-statement-import,/odoo/external-src/calendar,/odoo/external-src/commission,/odoo/external-src/community-data-files,/odoo/external-src/connector-cmis,/odoo/external-src/connector-ecommerce,/odoo/external-src/connector-magento,/odoo/external-src/connector-telephony,/odoo/external-src/connector,/odoo/external-src/contract,/odoo/external-src/crm,/odoo/external-src/data-protection,/odoo/external-src/delivery-carrier,/odoo/external-src/donation,/odoo/external-src/e-commerce,/odoo/external-src/edi,/odoo/external-src/event,/odoo/external-src/geospatial,/odoo/external-src/hr-timesheet,/odoo/external-src/hr,/odoo/external-src/knowledge,/odoo/external-src/l10n-netherlands,/odoo/external-src/maintenance,/odoo/external-src/management-system,/odoo/external-src/margin-analysis,/odoo/external-src/multi-company,/odoo/external-src/mis-builder,/odoo/external-src/partner-contact,/odoo/external-src/product-attribute,/odoo/external-src/product-variant,/odoo/external-src/project-agile,/odoo/external-src/project-reporting,/odoo/external-src/project,/odoo/external-src/purchase-reporting,/odoo/external-src/purchase-workflow,/odoo/external-src/intrastat-extrastat,/odoo/external-src/queue,/odoo/external-src/reporting-engine,/odoo/external-src/rest-framework,/odoo/external-src/rma,/odoo/external-src/sale-financial,/odoo/external-src/sale-reporting,/odoo/external-src/sale-workflow,/odoo/external-src/server-auth,/odoo/external-src/social,/odoo/external-src/stock-logistics-barcode,/odoo/external-src/stock-logistics-reporting,/odoo/external-src/stock-logistics-transport,/odoo/external-src/stock-logistics-warehouse,/odoo/external-src/stock-logistics-workflow,/odoo/external-src/web,/odoo/external-src/webkit-tools,/odoo/external-src/website-cms,/odoo/external-src/account-reconcile,/odoo/external-src/operating-unit
      - VIRTUAL_HOST=$HOST
      - VIRTUAL_PORT=8069,8072/longpolling
    networks:
      - docky10wh_default
    expose:
      - 8069
      - 8072
    volumes:
      - "nfsmount:/odoo"
      - ./data/addons:/data/odoo/addons
      - ./data/filestore:/data/odoo/filestore
      - ./data/sessions:/data/odoo/sessions
#    command: ["odoo"]
    command: ["bash"]
    stdin_open: true
    tty: true

#  nginx:
#    image: nginx
#    #    labels:
#    #      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
#    container_name: nginx
#    restart: unless-stopped
#    depends_on:
#      - odoo
#    ports:
#      - "80:80"
#    #      - "443:443"
#    volumes:
#      - ${NGINX_FILES_PATH}/conf.d:/etc/nginx/conf.d
#      - ${NGINX_FILES_PATH}/vhost.d:/etc/nginx/vhost.d
#      - ${NGINX_FILES_PATH}/html:/usr/share/nginx/html
#      - ${NGINX_FILES_PATH}/certs:/etc/nginx/certs:ro
#
#  nginx-gen:
#    image: jwilder/docker-gen
#    command: -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
#    container_name: nginx-gen
#    restart: unless-stopped
#    volumes:
#      - ${NGINX_FILES_PATH}/conf.d:/etc/nginx/conf.d
#      - ${NGINX_FILES_PATH}/vhost.d:/etc/nginx/vhost.d
#      - ${NGINX_FILES_PATH}/html:/usr/share/nginx/html
#      - ${NGINX_FILES_PATH}/certs:/etc/nginx/certs:ro
#      - /var/run/docker.sock:/tmp/docker.sock:ro
#      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro

volumes:
  data-db10:
  nfsmount:
    driver: local
    driver_opts:
      type: nfs
      o: addr=host.docker.internal,rw,nolock,hard,nointr,nfsvers=3
      device: ":/Volumes/Case-Sens/voodoo/docky12/odoo"
