
services:
  odoo:
    build: ./odoo/
    stdin_open: true
    tty: true
    depends_on:
      - db
    environment:
      - DB_USER=odoo
      - DB_PASS=odoo
      - DB_NAME=ammer01
      - DB_FILTER=ammer01
      - LOG_HANDLER=:INFO
      - MIGRATE=false
      - PYTHONDONTWRITEBYTECODE=True
      - LOCAL_USER_ID=1001
      - ADMIN_PASSWD=ButNoS1mpler
      - RUNNING_ENV=dev
      - LIST_DB=True
      - LIMIT_TIME_CPU=6000
      - LIMIT_TIME_REAL=12000
      - SERVER_WIDE_MODULES=web,web_kanban,queue_job
      - DB_HOST=db
      - WORKERS=0
      - ADDONS_PATH=/odoo/local-src,/odoo/src/addons,/odoo/links,/odoo/src/odoo/addons,/odoo/external-src/account-analytic,/odoo/external-src/account-closing,/odoo/external-src/account-consolidation,/odoo/external-src/account-financial-reporting,/odoo/external-src/account-financial-tools,/odoo/external-src/account-fiscal-rule,/odoo/external-src/account-invoicing,/odoo/external-src/account-reconcile,/odoo/external-src/ammer-addons,/odoo/external-src/bank-payment,/odoo/external-src/bank-statement-import,/odoo/external-src/bdu-addons,/odoo/external-src/calendar,/odoo/external-src/commission,/odoo/external-src/community-data-files,/odoo/external-src/connector,/odoo/external-src/connector-cmis,/odoo/external-src/connector-ecommerce,/odoo/external-src/connector-interfaces,/odoo/external-src/connector-jira,/odoo/external-src/contract,/odoo/external-src/crm,/odoo/external-src/data-protection,/odoo/external-src/delivery-carrier,/odoo/external-src/donation,/odoo/external-src/e-commerce,/odoo/external-src/edi,/odoo/external-src/event,/odoo/external-src/geospatial,/odoo/external-src/hr,/odoo/external-src/hr-timesheet,/odoo/external-src/intrastat-extrastat,/odoo/external-src/knowledge,/odoo/external-src/l10n-netherlands,/odoo/external-src/licensed-modules,/odoo/external-src/magnus-addons,/odoo/external-src/maintenance,/odoo/external-src/management-system,/odoo/external-src/margin-analysis,/odoo/external-src/mis-builder,/odoo/external-src/misc,/odoo/external-src/misset-addons,/odoo/external-src/multi-company,/odoo/external-src/nsm-addons,/odoo/external-src/operating-unit,/odoo/external-src/partner-contact,/odoo/external-src/product-attribute,/odoo/external-src/product-variant,/odoo/external-src/project,/odoo/external-src/project-agile,/odoo/external-src/project-reporting,/odoo/external-src/purchase-reporting,/odoo/external-src/purchase-workflow,/odoo/external-src/queue,/odoo/external-src/reporting-engine,/odoo/external-src/rest-framework,/odoo/external-src/rma,/odoo/external-src/sale-financial,/odoo/external-src/sale-reporting,/odoo/external-src/sale-workflow,/odoo/external-src/server-auth,/odoo/external-src/server-tools,/odoo/external-src/server-ux,/odoo/external-src/social,/odoo/external-src/stock-logistics-barcode,/odoo/external-src/stock-logistics-reporting,/odoo/external-src/stock-logistics-transport,/odoo/external-src/stock-logistics-warehouse,/odoo/external-src/stock-logistics-workflow,/odoo/external-src/vertical-agriculture,/odoo/external-src/vertical-association,/odoo/external-src/vertical-construction,/odoo/external-src/vertical-edition,/odoo/external-src/vertical-education,/odoo/external-src/vertical-isp,/odoo/external-src/vertical-medical,/odoo/external-src/vertical-publishing,/odoo/external-src/vertical-travel,/odoo/external-src/web,/odoo/external-src/webkit-tools,/odoo/external-src/website-cms
      - VIRTUAL_HOST=docky10whmbp
      - VIRTUAL_PORT=8069,8072/longpolling
    expose:
      - 8069
      - 8072
    volumes:
      - ./data/addons:/data/odoo/addons:cached
      - ./data/filestore:/data/odoo/filestore:cached
      - ./data/sessions:/data/odoo/sessions:cached
      - "nfsmount:/odoo"
    #    command: ["odoo"]
    command: ["bash"]

  db:
    environment:
      - POSTGRES_USER=odoo
      #      - POSTGRES_DB=db
      - POSTGRES_HOST_AUTH_METHOD=trust
    image: postgres:9.6
    restart: unless-stopped
    volumes:
      - "data-db:/var/lib/postgresql/data"
    ports:
      - 5432:5432

  nginx:
    image: nginx
#    labels:
#      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    container_name: nginx
    restart: unless-stopped
    depends_on:
      - odoo
    ports:
      - "80:80"
#      - "443:443"
    volumes:
      - ${NGINX_FILES_PATH}/conf.d:/etc/nginx/conf.d
      - ${NGINX_FILES_PATH}/vhost.d:/etc/nginx/vhost.d
      - ${NGINX_FILES_PATH}/html:/usr/share/nginx/html
      - ${NGINX_FILES_PATH}/certs:/etc/nginx/certs:ro

  nginx-gen:
    image: jwilder/docker-gen
    command: -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    container_name: nginx-gen
    restart: unless-stopped
    volumes:
      - ${NGINX_FILES_PATH}/conf.d:/etc/nginx/conf.d
      - ${NGINX_FILES_PATH}/vhost.d:/etc/nginx/vhost.d
      - ${NGINX_FILES_PATH}/html:/usr/share/nginx/html
      - ${NGINX_FILES_PATH}/certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro

volumes:
  data-db:
  nfsmount:
    driver: local
    driver_opts:
      type: nfs
      o: addr=host.docker.internal,rw,nolock,hard,nointr,nfsvers=3
      device: ":/Volumes/Case-Sens/voodoo/docky10wh/odoo"
version: '3'
