#networks:
#    base_default:
#      external: true
#    backend:
#      driver: bridge
services:
  db10:
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_DB=db
    image: postgres:10
    restart: unless-stopped
#    networks:
#      backend:
#        aliases:
#          - pg10
    volumes:
      - .db/data/:/var/lib/postgresql/data
#      - .db/socket/:/var/run/postgresql/
    ports:
      - 5432:5432
  odoo:
    build: odoo
    image: app_backend_odoo:latest
    environment:
      - MIGRATE=false
      - PYTHONDONTWRITEBYTECODE=True
      - LOCAL_USER_ID=1001
      - DB_USER=odoo
      - DB_PASS=odoo
      - DB_NAME=db
      - RUNNING_ENV=dev
#      - MARABUNTA_MODE=demo
      - VIRTUAL_HOST=app-backend
      - VIRTUAL_PORT=8069,8072/longpolling
#    user: odoo
    expose:
      - 8069
      - 8072
#    networks:
#      - base_default
#      - backend
    volumes:
      - ./odoo:/odoo
      - ./data/addons:/data/odoo/addons
      - ./data/filestore:/data/odoo/filestore
      - ./data/sessions:/data/odoo/sessions
    command: ["bash"]
    stdin_open: true
    tty: true
version: '3'
